### PR TITLE
add verification and dynamic player score saveing

### PR DESCRIPTION
**Pull request by LeviUniAcc**
Part of Gamify-IT/issues#251

To test run the docker compose and try to access the backend.

Without login you should receive a `500` if cookie is not set. If the token in the cookie is invalid you should get a `401`

Also if you access lecturer-only endpoints (for example create a minigame) as student you receive a `401`.

Keycloak lecturer user is: `lecturer` `lecturer`

The tests are too complicated to be done in this task. They will follow soon.

### CODE REVIEW

**Review by madebyTimo — APPROVED** [review]

**Review by marlau97 — APPROVED** [review]

**Comment by delvh** [comment]
> Without login you should receive a 500

Please tell me you mean `400`?

**Comment by madebyTimo** [comment]
No, we didn't found a option to handle that better

**Comment by delvh** [comment]
What do you mean?
How **can't** there be a solution to handle that better?

**Comment by madebyTimo** [comment]
most likely there is one but we didn't found it. In my opinion this can be a task for the next sprint

**Comment by delvh** [comment]
```java
try {
 $VALIDATION
} catch (Exception e) {
  throw new ResponseStatusException(HttpStatus.NOT_FOUND, "cookie not set");
}
```
?

**Comment by delvh** [comment]
Ah no, I know what your problem is: `@CookieValue(required = false) String authCookie`

**Comment by delvh** [comment]
But shouldn't this already return a 400?

**Comment by madebyTimo** [comment]
No in my test it returned a 500. But cause this is a case that should never occur if you access the project via the landing page, we decided to solve this another time

**Comment by madebyTimo** [comment]
It seems like you were right, it returns a 400

**Pull request merged**
