### PR TITLE
Fix docker

### PR DESCRIPTION
**Pull request by Fa8Bit**

### CODE REVIEW

**Review by opourazar — APPROVED** [review]
Necessary changes based on our findings about the working versions.
NOTE: Some checks didn't run through.

**Comment by opourazar** [comment]
The comments and suggestions for this [PR](https://github.com/Gamify-IT/regexgame-backend/pull/10) indicate that we need to reconsider our use of the respective files.

**Comment by Fa8Bit** [comment]
Finished changes, can be merged, pls merge as "squash and merge"

**Review by eisenmls — APPROVED** [review]
looks good

**Pull request merged**
